name: PR Template Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Debug PR Body
        run: |
          echo "Event Path: $GITHUB_EVENT_PATH"
          cat $GITHUB_EVENT_PATH
          PR_BODY=$(cat $GITHUB_EVENT_PATH | jq -r '.pull_request.body')
          echo "PR Body: $PR_BODY"

      - name: Check PR Template
        run: |
          PR_BODY=$(cat $GITHUB_EVENT_PATH | jq -r '.pull_request.body')
          if [[ -z "$PR_BODY" || "$PR_BODY" == *"Description"* ]]; then
            echo "PR template is not filled. Please fill it."
            exit 1
          else
            echo "PR template is filled correctly."
          fi
